### ISSUE TITLE
Possible GPL violation?

### ISSUE THREAD

**Issue by scruss** [cybernesto/sid-arduino-lib#1]
Christoph Haberer's [original](http://www.roboterclub-freiburg.de/atmega_sound/atmegaSID.html) is GPL, not LGPL. Please check with him if it's okay for your derived version to have a more permissive licence

**Comment by cybernesto** [comment]
The change was done without knowing the consequences of this decision, based only on the premise that the program stopped being one, by converting it into a library. I asked the author, and even though he accepted the changed license, the original license would not allow such a change, so that it can be considered invalid. I corrected this in the last commit. Thanks for your remark.
